version: "3.7"

services: 
  calu_database:
    image: postgres
    container_name: calu_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=calendario-unificado
    volumes:
      - pgdata:/data/postgress
  app:
    build: .
    container_name: calendario-unificado
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local